main: com.github.dawsonvilamaa.beaconwaypoint.Main
name: BeaconWaypoints
version: 1.3.0
api-version: 1.14
author: Dawson Vilamaa
description: Allows players to set waypoints at beacons
commands:
  waypoint:
    aliases: [wp, waypoints]
    description: Add or remove a waypoint
    usage: /waypoint <name> <public | private>
    permission: BeaconWaypoints.createWaypoints
    permission-message: You don't have permission to use that command
    
permissions:
  BeaconWaypoints.createWaypoints:
    description: Allows players to create waypoints
    default: true
  BeaconWaypoints.useWaypoints:
    description: Allows players to use waypoints
    default: true
  BeaconWaypoints.usePrivateWaypoints:
    description: Allows players to create and teleport to private waypoints
    default: true
  BeaconWaypoints.breakWaypointBeacons:
    description: Allows players to break beacons that have waypoints
    default: true
  BeaconWaypoints.manageAllWaypoints:
    description: Allows players to edit or remove all public waypoints and corresponding beacons
    default: op
  BeaconWaypoints.reload:
    description: Allows players to reload the config
    default: op